version: '3.8'
services:
  api:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Pass@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
